version: '2'

services:
  crypto_tracker_nginx:
    container_name: crypto_tracker_nginx_container
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    volumes:
     - ./ui/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - crypto_tracker_flask
    # develop:
    #   watch: #https://docs.docker.com/compose/file-watch/ #docker compose watch
    #     - action: sync
    #       path: ./ui/dist
    #       target: /usr/share/nginx/html
    #       ignore:
    #         - venv/
    #     - action: rebuild
    #       path: requirements.txt

  crypto_tracker_flask:
    container_name: crypto_tracker_flask_container
    restart: always
    image: flask
    build: ./server
    volumes:
     - ./server:/usr/src/app/server
    env_file:
     - .env
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./flask_service
    #       target: /usr/src/app/algo_flask
    #       ignore:
    #         - node_modules/
    #     - action: rebuild
    #       path: package.json