version: '1'

services:
  crypto_tracker_nginx:
    container_name: crypto_tracker_nginx_container
    restart: always
    image: nginx
    build:
      context: .
      dockerfile: deployment/Dockerfile_ui
    volumes:
     - ./ui/dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"
      - "444:444"
      - "445:445"
    depends_on:
      - mdi_ms_flask
      # - sentiment_ms
      - backtesting_ms_flask
    develop:
      watch: #https://docs.docker.com/compose/file-watch/ #docker compose watch
        - action: sync
          path: ./ui/dist
          target: /usr/share/nginx/html
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  mdi_ms_flask:
    container_name: mdi_ms_flask_container
    restart: always
    image: flask
    build: 
      context: ./mdi_ms
      dockerfile: ../deployment/Dockerfile_mdi_ms
    volumes:
     - ./mdi_ms:/usr/src/app/mdi_ms
    env_file:
     - .env
    develop:
      watch:
        - action: sync
          path: ./mdi_ms
          target: /usr/src/app/mdi_ms
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt

  # sentiment_ms_flask:
  #   container_name: sentiment_ms_flask_container
  #   restart: always
  #   image: flask
  #   build: 
  #     context: ./sentiment_ms
  #     dockerfile: ../deployment/Dockerfile_sentiment_ms
  #   volumes:
  #    - ./sentiment_ms:/usr/src/app/sentiment_ms
  #   env_file:
  #    - .env
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./sentiment_ms
  #         target: /usr/src/app/sentiment_ms
  #         ignore:
  #           - venv/
  #       - action: rebuild
  #         path: requirements.txt

  backtesting_ms_flask:
    container_name: backtesting_ms_flask_container
    restart: always
    image: flask
    build: 
      context: ./backtesting_ms
      dockerfile: ../deployment/Dockerfile_backtesting_ms
    volumes:
     - ./backtesting_ms:/usr/src/app/backtesting_ms
    env_file:
     - .env
    develop:
      watch:
        - action: sync
          path: ./backtesting_ms
          target: /usr/src/app/backtesting_ms
          ignore:
            - venv/
        - action: rebuild
          path: requirements.txt